desktop-app/patches

qtbase_5_12_8.diff

Fixes https://github.com/telegramdesktop/tdesktop/issues/7773

Fix korean fonts

---

qtbase_5_12_8.diff
qtstyleplugins.diff

To avoid https://github.com/FedoraQt/QGnomePlatform/issues/63

Move preview support to QGtk3FileDialogHelper class

---

qtbase_xkbfix_5_12_8.diff
qtwayland_xkbfix_5_12_8.diff

Fixes https://github.com/telegramdesktop/tdesktop/issues/6645

Backport fix for keybindings with non-english layout on Wayland

---

qtwayland_5_12_8.diff

Fixes https://github.com/telegramdesktop/tdesktop/issues/7862

Backport a fix for popup menus

---

qtbase_5_12_8/0028-fix-contextmenu-on-titlebar.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/7045

Fix context menu on titlebar

---

qtbase_5_12_8/0008-fix-cjk-font-fallback.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/8164

Add Amharic font to the fallback list

---

qtbase_5_15_2/0032-always-use-xft-font-conf.patch
qtbase_5_15_2/0033-get-dpi-from-xsettings.patch

1. Let Qt to always get font rendering settings from X resources
2. Get DPI from X Settings when availabe

Add patches for better environment integration on Linux

---

qtbase_5_15_2/0046-gtk-as-last-resort.patch

This allows WM-only environments to have icon theme and advanced file dialog

Use gtk as the last resort

---

glibmm.patch

Previously that was a part of glibmm helper in lib_base

Backport Glib::Variant<std::tuple> support to glibmm

---

qtbase_6_2_2/0048-fix-http-proxy.patch

Should fix telegramdesktop/tdesktop#17316.

Add fix for HTTP proxy handling

---

qtbase_6_4_0/0036-fix-crash-when-creating-widget-in-destructor.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/25074

Fix a crash when creating widget in destructor

---

qtbase_6_4_1/0035-Revert-Do-not-use-client-side-data-pointers-in-qopen.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/25432

Fix Qt OpenGL regression

---

qtbase_6_3_2/0038-lcms2.patch
qtbase_6_3_2/0039-no-quality-loss-when-scaling-images.patch
qtbase_6_4_1/0039-no-quality-loss-when-scaling-images.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/25436

Don't do lossy format conversation after scaling images

---

qtbase_5_15_7/0025-respect-short-time-format-on-windows.patch
qtbase_6_3_2/0040-respect-short-time-format-on-windows.patch
qtbase_6_4_1/0040-respect-short-time-format-on-windows.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/25640

Fix respecting short time format on Windows

---

qtbase_5_15_8/0003-fix-cjk-font-fallback.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/25714

Fix fix-cjk-font-fallback patch for Qt 5.15.8

---

qtbase_5_15_8/0003-fix-windows-font-fallback.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/25846

Use modern API only for default font size

---

qtbase_6.5.0/0028-fix-startsystemmoveresize-on-x11.patch
qtbase_6.5.0/0029-fix-scrolling-on-x11.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/10348, https://github.com/telegramdesktop/tdesktop/issues/17254

Add fixes for window moving and scrolling on X11

---

qtbase_6.5.0/0021-optional-gtk.patch

And avoid linking the libraries itselves to spot such places early next time

Wrap missed functions in optional-gtk patch

---

qtbase_6.5.0/0021-optional-gtk.patch

It was missed as forgotten to check Qt build with all features enabled

Wrap the last missed function in optional-gtk

---

qtbase_6.5.2/0013-nicer-platformtheme-choosing.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/26370

Make platform theme choosing even more nicer

---

qtbase_5.15.15/0027-backport-dpi-change-fixes.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/28503

Backport another HiDPI fix to Qt 5.15

---

qtwayland_6.8.1/0001-always-fractional-scale.patch

Fixes https://github.com/telegramdesktop/tdesktop/issues/28894

Fix DPR with portrait orientation on Wayland
